# Generated by Django 3.2.7 on 2021-09-29 05:42

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='armierung',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ausklinkung',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='armierung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ausklinkung',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ausschnitt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='bohrung',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='images/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='length',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='polierte_kante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
