# Generated by Django 3.2.7 on 2021-09-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210929_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_tiles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
