# Generated by Django 3.2.7 on 2021-09-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210930_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_tiles',
            new_name='is_tile',
        ),
    ]
