# Generated by Django 3.2.7 on 2021-10-05 12:01

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211005_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
