# Generated by Django 3.2.7 on 2021-10-05 12:04

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
