# Generated by Django 3.2.8 on 2021-10-07 19:00

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211007_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
