# Generated by Django 3.2.8 on 2021-10-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='tag',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
